/**
 * CONFIGURACIÓN DE LA INTERFAZ
 * Pegue en DIRECCION_APLICACION la dirección terminada en /exec del despliegue de Google Apps Script.
 */
window.CONFIGURACION_FLOTAS = Object.freeze({
  VERSION: '3.5.0',
  MODO: 'automatico',
  MODO_MODULAR: true,
  DIRECCION_APLICACION: 'https://script.google.com/macros/s/AKfycbx98wcp4u-6DDZc4UYbw49-j5wJWHqwqwCy8dRsvHRthv2Pz5p2lQrXUE5mlkXkUVPh/exec',
  CLAVE_ALMACENAMIENTO_LOCAL: 'sistema_gestion_flotas_base_local_v3',
  CLAVE_SESION_LOCAL: 'sistema_gestion_flotas_sesion_v3',
  TIEMPO_ESPERA_MILISEGUNDOS: 25000,
  CACHE_MODULOS_MILISEGUNDOS: 300000,
  CACHE_MAXIMA_ANTIGUEDAD_MILISEGUNDOS: 86400000,
  CLAVE_CACHE_MODULOS_LOCAL: 'sistema_gestion_flotas_cache_modulos_v1',
  CACHE_LOCAL_MAXIMO_ENTRADAS: 42,
  CACHE_LOCAL_MAXIMO_BYTES: 3500000,
  CACHE_TIEMPO_REAL_MILISEGUNDOS: 1800,
  PRECARGA_MAXIMA_CONSULTAS: 0,
  INTERVALO_GPS_MILISEGUNDOS: 4000,
  INTERVALO_TIEMPO_REAL_MILISEGUNDOS: 4000,
  INTERVALO_TIEMPO_REAL_OCULTO_MILISEGUNDOS: 30000,
  RETARDO_REINTENTO_TIEMPO_REAL_MAXIMO_MILISEGUNDOS: 30000,
  DISTANCIA_MINIMA_ENVIO_GPS_METROS: 6,
  INTERVALO_CONEXION_MILISEGUNDOS: 20000,
  INTERVALO_NOTIFICACIONES_MILISEGUNDOS: 30000,
  ANTIGUEDAD_UBICACION_ACTIVA_MILISEGUNDOS: 120000,
  ANTIGUEDAD_CONEXION_ACTIVA_MILISEGUNDOS: 90000,
  TOLERANCIA_GPS_IMPRECISA_FIN_METROS: 500,
  RESOLVER_DIRECCIONES: true,
  DIRECCION_GEOCODIFICACION_INVERSA: 'https://nominatim.openstreetmap.org/reverse',
  DIRECCION_BUSQUEDA_DIRECCIONES: 'https://nominatim.openstreetmap.org/search',
  PAIS_BUSQUEDA_DIRECCIONES: 'cl',
  MINIMO_CARACTERES_DIRECCION: 3,
  ESPERA_BUSQUEDA_DIRECCION_MILISEGUNDOS: 450,
  CENTRO_MAPA: [-33.4489, -70.6693],
  NIVEL_ACERCAMIENTO_MAPA: 12
});
